### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by le2Ks** [ocvcoin/ocvcoin#1]
Hi, 

There is an 'Assertion Failed' error when starting the wallet, mentioning that the genesis blocks for all mainnet, testnet and regtest chain aren't correct.
IT seems that the chainparams.cpp file differs from the version running on the  official node and explorer.

**Comment by ocvcoin** [comment]
hi
Did you run the pow_server.py before running it?

https://github.com/ocvcoin/pow_server
