### ISSUE TITLE
Error whilst compiling ocvcoind

### ISSUE THREAD

**Issue by Xarthie** [ocvcoin/ocvcoin#3]
I'm getting an error whilst compiling the ocvcoind. The error is thrown when Make hits block.cpp
Looking error, and judging by it, it seems to be related to opencv2.

I'm trying to compile this on Ubuntu 18 with all dependencies installed.
I've tried using my own libs as well as the once supplied in the depends-folder, but neither made a difference.. Still getting the same error. 

This is the error i'm talking about:
  CXXLD    ocvcoind
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `CBlockHeader::GetHash() const':
block.cpp:(.text+0x146): undefined reference to `cv::Mat::zeros(int, int, int)'
block.cpp:(.text+0x2a2): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x342): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x3e2): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x7e3): undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
block.cpp:(.text+0x8d9): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x989): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0xadb): undefined reference to `cv::medianBlur(cv::_InputArray const&, cv::_OutputArray const&, int)'
block.cpp:(.text+0xb7c): undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
block.cpp:(.text+0xb84): undefined reference to `cv::String::deallocate()'
block.cpp:(.text+0xcdc): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0xd72): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0xe06): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0xfd9): undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
block.cpp:(.text+0x10d1): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x1181): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x1299): undefined reference to `cv::bilateralFilter(cv::_InputArray const&, cv::_OutputArray const&, int, double, double, int)'
block.cpp:(.text+0x13e5): undefined reference to `cv::filter2D(cv::_InputArray const&, cv::_OutputArray const&, int, cv::_InputArray const&, cv::Point_<int>, double, int)'
block.cpp:(.text+0x1516): undefined reference to `cv::blur(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, cv::Point_<int>, int)'
block.cpp:(.text+0x1634): undefined reference to `cv::GaussianBlur(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
block.cpp:(.text+0x1739): undefined reference to `cv::medianBlur(cv::_InputArray const&, cv::_OutputArray const&, int)'
block.cpp:(.text+0x17da): undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
block.cpp:(.text+0x17e2): undefined reference to `cv::String::deallocate()'
block.cpp:(.text+0x1964): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x19fc): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x1a94): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x1b2c): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text+0x1bc4): undefined reference to `cv::fastFree(void*)'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o):block.cpp:(.text+0x1c5a): more undefined references to `cv::fastFree(void*)' follow
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `CBlockHeader::GetHash() const':
block.cpp:(.text+0x1e3f): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x1e51): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x1e63): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x1ed6): undefined reference to `cv::bilateralFilter(cv::_InputArray const&, cv::_OutputArray const&, int, double, double, int)'
block.cpp:(.text+0x1ee5): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x1f57): undefined reference to `cv::fastNlMeansDenoisingColored(cv::_InputArray const&, cv::_OutputArray const&, float, float, int, int)'
block.cpp:(.text+0x1fdf): undefined reference to `cv::GaussianBlur(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
block.cpp:(.text+0x208b): undefined reference to `cv::filter2D(cv::_InputArray const&, cv::_OutputArray const&, int, cv::_InputArray const&, cv::Point_<int>, double, int)'
block.cpp:(.text+0x209a): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x20a9): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x20b8): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x20c7): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text+0x20d6): undefined reference to `cv::Mat::deallocate()'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o):block.cpp:(.text+0x20e5): more undefined references to `cv::Mat::deallocate()' follow
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `CBlockHeader::GetHash() const':
block.cpp:(.text+0x21ca): undefined reference to `cv::blur(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, cv::Point_<int>, int)'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `cv::String::String(char const*)':
block.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x49): undefined reference to `cv::String::allocate(unsigned long)'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `cv::Mat::~Mat()':
block.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x86): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0xa1): undefined reference to `cv::Mat::deallocate()'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `cv::MatExpr::~MatExpr()':
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0xa7): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x134): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x19e): undefined reference to `cv::fastFree(void*)'
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x1c5): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x1d8): undefined reference to `cv::Mat::deallocate()'
block.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x1ed): undefined reference to `cv::Mat::deallocate()'
libocvcoin_consensus.a(libocvcoin_consensus_a-block.o): In function `CBlockHeader::GetHash() const [clone .cold]':
block.cpp:(.text.unlikely+0x4): undefined reference to `cv::String::deallocate()'
block.cpp:(.text.unlikely+0xc1): undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
Makefile:5284: recipe for target 'ocvcoind' failed

Does any of this seem familiar to anyone?

**Comment by ocvcoin** [comment]
do you get this error when you run `UBUNTU_AUTO_BUILD_AND_INSTALL.sh`?

**Comment by Xarthie** [comment]
Yeah i do. I get the same error regardless of method of compilation, unfortunately..

**Comment by ocvcoin** [comment]
today i tried this script again on ubuntu 18 minimal clean installation. no problems. script seems to work fine.


Just run this command:
```
wget -qO - https://raw.githubusercontent.com/ocvcoin/ocvcoin/master/UBUNTU_AUTO_BUILD_AND_INSTALL.sh | sudo bash

```

**Comment by Xarthie** [comment]
Worked just fine with the UBUNTU shell after i did some tweaks.. ty :)
